## Introduction to Python Exercises

Before you turn this problem in, make sure everything runs as expected. First, restart the kernel (in the menubar, select Kernel → Restart) and then run all cells (in the menubar, select Cell → Run All).  You can speak with others regarding the assignment but all work must be your own. 


### This is a 30 point assignment graded from answers to questions and automated tests that should be run at the bottom. Be sure to clearly label all of your answers and commit final tests at the end. If you attempt to fake passing the tests you will receive a 0 on the assignment and it will be considered an ethical violation. (Note, not all questions have tests).

In [35]:
NAME = "Ritu Chandwani"
COLLABORATORS = ["Alyssa Hacker"]  #You can speak with others regarding the assignment, but all typed work must be your own.

In [36]:
# If you have trouble loading your unittests below, 
#!conda config --add channels conda-forge

In [9]:
#!conda install --yes ipython_unittest

### This Loads a Testing Array 
- This runs tests against your b array.  If you complete the assingment correctly, you will pass the tests. 
- **If you attempt to fake passing the tests you will receive a 0 on the assignment and it will be considered an ethical violation.**

In [37]:
%load_ext ipython_unittest
#This runs tests against your b array.  If you complete the assingment correctly, you will pass the tests.

The ipython_unittest extension is already loaded. To reload it, use:
  %reload_ext ipython_unittest

## Exercises - For and If.

(1). Write a program which create a list called `fivetoten` of all numbers from 5 to 10 (inclusive).

In [53]:
z=range(5,11,1);
fivetoten=[]
for i in z:
    fivetoten.append(i)
print(fivetoten)

[5, 6, 7, 8, 9, 10]

(2). Write a program which uses a for loop and if statements to create a list called `divby7` of all numbers from 1-50 that are divisible by 7.
Hint: 14 is divisible by 7 if 14%7==0.

In [39]:
#Answer question 2 here
divby7=[]
z=range(1,51)
for i in z:
    if(i%7 == 0):
        divby7.append(i)
print(divby7)

[7, 14, 21, 28, 35, 42, 49]

(3). Write a program which uses a for loop and if statements create a list `divby7not5` of all numbers which are divisible by 7 but are not a multiple of 5, between 10000 and 10100 (both included).

In [40]:
#Answer question 3 here.
divby7not5=[]
z=range(10000,10101,1)
for i in z:
    if(i%7==0 and i%5!=0):
        divby7not5.append(i)
print(divby7not5)

[10003, 10017, 10024, 10031, 10038, 10052, 10059, 10066, 10073, 10087, 10094]

## Exercises - Functions

(4). Create a function `divby2` that accepts a list and returns all values from that list that are divisible by 2.  For example, passing the list  `numbers = [3, 12, 91, 33, 21, 34, 54, 34, 34, 54]` should return a list. Generate a new list `divby2` that includes only numbers that are divisible by 2.

In [41]:
#Define your function here.
demoList=[]
def divby2(listDemo):
    for i in listDemo:
        if i%2 == 0:
            demoList.append(i)
    return demoList

input=[3, 12, 91, 33, 21, 34, 54, 34, 34, 54]
print(divby2(input))

[12, 34, 54, 34, 34, 54]

In [42]:
#Execute this code to assign divby2 to the correct values. 
numbers = [3, 12, 91, 33, 21, 34, 54, 34, 34, 54]
divby2=divby2(numbers)
print(divby2)

[12, 34, 54, 34, 34, 54, 12, 34, 54, 34, 34, 54]

(5) Create an external module for your `divby2` function called `myutilities.py`.  Import myutilities as mu, such that that following runs.

In [43]:
#After importing this should work. (Feel free to add code to reimport)
import myutilities as mu
numbers = [3, 12, 91, 33, 21, 34, 54, 34, 34, 54]
divby2mod=mu.divby2(numbers)
print(divby2mod)

[12, 34, 54, 34, 34, 54]

## Exercises-Titanic

The following exercises will use the titanic data from Kaggle.  I've included it in the input folder just like Kaggle.

In [44]:
import numpy as np 
import pandas as pd 

# Input data files are available in the "../input/" directory.
# Let's input them into a Pandas DataFrame
train = pd.read_csv("../input/train.csv")
test  = pd.read_csv("../input/test.csv")



(6). While we can submit our answer to Kaggle to see how it will perform, we can also utilize our test data to assess accuracy. Accuracy is the percentage of predictions made correctly-i.e., the percentage of people in which our prediction regarding their survival. <br>Create columns in the training dataset `PredEveryoneDies` and `PredGender` with the same predictions which were included in the example notebook (06-intro-kaggle-baseline in the materials repository).

In [45]:
#Answer

train.loc[train['Sex'] == 'male', 'PredGender'] = 0
train.loc[train['Sex'] == 'female', 'PredGender'] = 1
train.PredGender.astype(int)
train['PredEveryoneDies']=0
PredTest=train['PredEveryoneDies']
PredTest

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
      ..
861    0
862    0
863    0
864    0
865    0
866    0
867    0
868    0
869    0
870    0
871    0
872    0
873    0
874    0
875    0
876    0
877    0
878    0
879    0
880    0
881    0
882    0
883    0
884    0
885    0
886    0
887    0
888    0
889    0
890    0
Name: PredEveryoneDies, Length: 891, dtype: int64

(7) Create variables `AccEveryoneDies` and `AccGender` using a calculation of accuracy of predictions for the `training` dataset.

In [46]:


from sklearn.metrics import accuracy_score

pred_value=train['PredEveryoneDies']
true_value=train['Survived']

AccEveryoneDies=accuracy_score(true_value,pred_value,normalize=True)*100
print(AccEveryoneDies)

Z=train['PredGender']
AccGender=accuracy_score(true_value,Z,normalize=True)*100

print(AccGender)

61.6161616162
78.6756453423

(8). Notice how we are utilizing the code to select out the `passengerID` and the `Survived` column and generating a submission file over and over? This is in need of a function.  Create a `generate_submission` function that accepts a DataFrame, a target column, and a filename and writes out the submission file with just the `passengerID` and the `Survived` columns, where the survived column is equal to the target column. It should then return a DataFrame with the `passengerID` and the `Survived` columns.

Executeing the following:
`submitdie = generate_submission(train, 'PredEveryoneDies', 'submiteveryonedies.csv')`

Should return a dataframe with just `passengerID` and the `Survived` column.

In [47]:

def generate_submission(df,col,file):
        submission=  df.loc[:,['PassengerId',col]]
        submission.rename(columns={col:'Survived'}, inplace=True)
        submission.Survived.astype(int)
        submission.to_csv(file, index=False)
        return submission
    
   
generate_submission(train,'PredEveryoneDies','submiteveryonedies.csv')

     PassengerId  Survived
0              1         0
1              2         0
2              3         0
3              4         0
4              5         0
5              6         0
6              7         0
7              8         0
8              9         0
9             10         0
10            11         0
11            12         0
12            13         0
13            14         0
14            15         0
15            16         0
16            17         0
17            18         0
18            19         0
19            20         0
20            21         0
21            22         0
22            23         0
23            24         0
24            25         0
25            26         0
26            27         0
27            28         0
28            29         0
29            30         0
..           ...       ...
861          862         0
862          863         0
863          864         0
864          865         0
865          866         0
866          867         0
867          868         0
868          869         0
869          870         0
870          871         0
871          872         0
872          873         0
873          874         0
874          875         0
875          876         0
876          877         0
877          878         0
878          879         0
879          880         0
880          881         0
881          882         0
882          883         0
883          884         0
884          885         0
885          886         0
886          887         0
887          888         0
888          889         0
889          890         0
890          891         0

[891 rows x 2 columns]


(9). In accordance to the [women and children first](https://en.wikipedia.org/wiki/Women_and_children_first) protocol, we hypothesize that our model could be improved by including whether the individual was a child in addition to gender.  *After* coding survival based on gender, update your recommendation to prediction in the training dataset survival based on age. <br> <br>

In other words, your model should predict that a male child would survive.  

`train['PredGenderAge13']` should be the prediction incorporating both Gender and whether Age <  13.
`train['PredGenderAge18']` should be the prediction incorporating both Gender and whether Age <  18.
`AccGenderAge13` should be the accuracy of the age prediction, based on `train['PredGenderAge13']`. 
`AccGenderAge18` should be the accuracy of the age prediction, based on `train['PredGenderAge18']`.

In [48]:
from sklearn.metrics import accuracy_score
import pandas as pd

mean_age=train.Age.mean()
mean_age=int(mean_age)

train.loc[train.Age.isnull(),"Age"]=mean_age

print(mean_age)

train.loc[((train['Sex'] == 'male') & (train['Age'] < 13)) , 'PredGenderAge13'] = 1
train.loc[((train['Sex'] == 'male') & (train['Age'] >= 13)) , 'PredGenderAge13'] = 0
train.loc[train['Sex'] == 'female', 'PredGenderAge13'] =1

print(train.PredGenderAge13.mean())
pred_valueAge13=train.PredGenderAge13
true_value=train['Survived']

AccGenderAge13=accuracy_score(true_value,pred_valueAge13,normalize=True)*100
print(AccGenderAge13)


train.loc[((train['Sex'] == 'male') & (train['Age'] < 18)) | (train['Sex'] == 'female'), 'PredGenderAge18'] = 1
train.loc[((train['Sex'] == 'male') & (train['Age'] >= 18)) , 'PredGenderAge18'] = 0

print(train.PredGenderAge18.mean())
AccGenderAge18=accuracy_score(true_value,train.PredGenderAge18,normalize=True)*100
print(AccGenderAge18)

29
0.3939393939393939
79.2368125701
0.4175084175084175
77.3288439955

In [56]:
import pandas as pd
mean_age=test.Age.mean()
mean_age=int(mean_age)

test.loc[test.Age.isnull(),"Age"]=mean_age


test.loc[((test['Sex'] == 'male') & (test['Age'] < 13)) , 'PredGenderAge13'] = 1
test.loc[((test['Sex'] == 'male') & (test['Age'] >= 13)) , 'PredGenderAge13'] = 0
test.loc[train['Sex'] == 'female', 'PredGenderAge13'] =1
test.loc[test.PredGenderAge13.isnull(),"PredGenderAge13"]=0

print(test['PredGenderAge13'])
generate_submission(test,'PredGenderAge13','generateSubmission.csv')

0      0.0
1      1.0
2      1.0
3      1.0
4      0.0
5      0.0
6      0.0
7      0.0
8      1.0
9      1.0
10     1.0
11     1.0
12     0.0
13     0.0
14     1.0
15     1.0
16     0.0
17     0.0
18     1.0
19     1.0
20     0.0
21     1.0
22     1.0
23     0.0
24     1.0
25     1.0
26     0.0
27     0.0
28     1.0
29     0.0
      ...
388    0.0
389    1.0
390    0.0
391    0.0
392    0.0
393    1.0
394    1.0
395    0.0
396    1.0
397    0.0
398    0.0
399    1.0
400    0.0
401    0.0
402    1.0
403    0.0
404    1.0
405    0.0
406    0.0
407    0.0
408    0.0
409    1.0
410    0.0
411    0.0
412    1.0
413    0.0
414    0.0
415    1.0
416    1.0
417    1.0
Name: PredGenderAge13, Length: 418, dtype: float64

     PassengerId  Survived
0            892       0.0
1            893       1.0
2            894       1.0
3            895       1.0
4            896       0.0
5            897       0.0
6            898       0.0
7            899       0.0
8            900       1.0
9            901       1.0
10           902       1.0
11           903       1.0
12           904       0.0
13           905       0.0
14           906       1.0
15           907       1.0
16           908       0.0
17           909       0.0
18           910       1.0
19           911       1.0
20           912       0.0
21           913       1.0
22           914       1.0
23           915       0.0
24           916       1.0
25           917       1.0
26           918       0.0
27           919       0.0
28           920       1.0
29           921       0.0
..           ...       ...
388         1280       0.0
389         1281       1.0
390         1282       0.0
391         1283       0.0
392         1284       0.0
393         1285       1.0
394         1286       1.0
395         1287       0.0
396         1288       1.0
397         1289       0.0
398         1290       0.0
399         1291       1.0
400         1292       0.0
401         1293       0.0
402         1294       1.0
403         1295       0.0
404         1296       1.0
405         1297       0.0
406         1298       0.0
407         1299       0.0
408         1300       0.0
409         1301       1.0
410         1302       0.0
411         1303       0.0
412         1304       1.0
413         1305       0.0
414         1306       0.0
415         1307       1.0
416         1308       1.0
417         1309       1.0

[418 rows x 2 columns]

(10). Create a prediction file for the "women and children first" model in column` PredGenderAge13` and upload it to Kaggle.  Take a screen shot of your position. Put that screenshot in this repository and use markdown to show your results in the cell below.  The syntax for including a markdown picture is shown below.  

```
![]myscreenshot.png
```

# picture
![](myscreenshot.png)

(11). You should find that the AccGenderAge13 is better than AccGenderAge18. Create a new column `child` in the test and train DataFrames that is 1 if Age <  13 and 0 otherwise.  This is a *feature*.  We will talk more about features next time.

In [59]:
#Answer 
import numpy as np
train['child'] = np.where(train['Age']<13,1,0)
test['child'] = np.where(test['Age']<13,1,0)

In [60]:
%%unittest_main
class TestExercise3(unittest.TestCase):
    def test_forif1(self):
        self.assertTrue(fivetoten == [5,6,7,8,9,10])
    def test_forif2(self):
        self.assertTrue(divby7 == [7,14,21,28,35,42,49])
    def test_forif(self):
        self.assertTrue(divby7not5 == [10003, 10017, 10024, 10031, 10038, 10052, 10059, 10066, 10073, 10087, 10094])
    def test_functions(self):
        self.assertTrue(divby2 == [12, 34, 54, 34, 34, 54])
    def test_functions(self):
        self.assertTrue(divby2mod == [12, 34, 54, 34, 34, 54])
    def test_titanic1(self):
        self.assertAlmostEqual(AccEveryoneDies, 61.6161616162)
    def test_titanic2(self):
        self.assertAlmostEqual(AccGender, 78.6756453423)
    def test_titanic3(self):
        self.assertAlmostEqual(train['PredEveryoneDies'].mean(), 0.0)
    def test_titanic4(self):
        self.assertAlmostEqual(train['PredGender'].mean(), 0.35241301908)
    def test_titanic5(self):
        self.assertTrue(['PassengerId', 'Survived']==list(pd.read_csv('submiteveryonedies.csv').columns.values))
    def test_titanic6(self):
        self.assertAlmostEqual(train['PredGenderAge13'].mean(), 0.393939393939)
    def test_titanic7(self):
        self.assertAlmostEqual(train['PredGenderAge18'].mean(), 0.417508417508)
    def test_titanic8(self):
        self.assertAlmostEqual(AccGenderAge13, 79.2368125701)
    def test_titanic9(self):
        self.assertAlmostEqual(AccGenderAge18, 77.3288439955)
    def test_titanic10(self):
        self.assertTrue(train['child'].sum()==69)
    def test_titanic11(self):
        self.assertTrue(test['child'].sum()==25)

Success

...............
----------------------------------------------------------------------
Ran 15 tests in 0.011s

OK

In [ ]:
#This is a collection of all of the tests from the exercises above.